theme: congo
languageCode: en-AU
defaultContentLanguage: en
title: Limb central
enableEmoji: yes
summaryLength: 0
author: 
  bio: 'We are the Limbs from Brisbane, Australia'
  image: img/limbs.jpg
  links:
    #- twitter: https://twitter.com/
    #- facebook: https://facebook.com/
    #- linkedin: https://linkedin.com/
    #- youtube: https://youtube.com/
  name: The Limbs
taxonomies:
  tag: tags
params:
  article:
    editAppendPath: yes
    editURL: https://github.com/jpanther/congo/tree/dev/exampleSite/content/
    showBreadcrumbs: yes
    showEdit: yes
  homepage:
    layout: profile
    mainSections: samples
    showRecent: no
  list:
    groupByYear: no
    showBreadcrumbs: yes
menu:
  main:
    - name: Mark
      pageRef: mark
      weight: 10
    - name: Michelle
      pageRef: michelle
      weight: 20
    - name: Matthew
      pageRef: matthew
      weight: 30
    - name: Andy
      pageRef: andy
      weight: 40
# Can insert tags here too using the pageRef: tags

markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    noClasses: no
