[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"
  ignoreErrors = ["error-remote-getjson"]

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "AEST"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_ENV = "production"
